/*
  NOTA: Esta página é parte do fluxo de fechamento de caixa e não foi adicionada ao menu principal.
  Ela deve ser acessada a partir de um botão "Fechar Caixa" na página de Sessões de Caixa.

  Esta página assume a existência de uma tabela `cash_counts` com a seguinte estrutura:

  CREATE TABLE cash_counts (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cash_session_id bigint NOT NULL REFERENCES cash_sessions(id) UNIQUE,
      user_id bigint NOT NULL REFERENCES users(id),
      counted_amount bigint NOT NULL,
      details jsonb, -- para armazenar a contagem de cada denominação
      count_time timestampz DEFAULT now(),
      observations text
  );
*/
"use client";

import { useEffect, useState, useMemo } from "react";
import { createClient } from "@/lib/supabase/client";

const denominations = {
  notes: [100, 50, 20, 10, 5, 2],
  coins: [1, 0.50, 0.25, 0.10, 0.05]
};

type Counts = { [key: string]: number };

export default function CashCountPage() {
  const supabase = createClient();
  const [counts, setCounts] = useState<Counts>({});
  const [observations, setObservations] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [openSession, setOpenSession] = useState<{ id: number; initial_amount: number } | null>(null);

  useEffect(() => {
    async function findOpenSession() {
      setError(null);
      setLoading(true);
      const { data, error } = await supabase
        .from('cash_sessions')
        .select('id, initial_amount')
        .eq('status', 'open')
        .single();

      if (error || !data) {
        setError('Nenhuma sessão de caixa aberta encontrada. Abra um caixa para iniciar a contagem.');
      } else {
        setOpenSession(data);
      }
      setLoading(false);
    }
    findOpenSession();
  }, []);

  const total = useMemo(() => {
    return Object.entries(counts).reduce((acc, [key, quantity]) => {
      const value = parseFloat(key.split('_')[1]);
      return acc + (value * (quantity || 0));
    }, 0);
  }, [counts]);

  const handleCountChange = (value: number, type: 'notes' | 'coins', quantity: string) => {
    const key = `${type}_${value}`;
    setCounts(prev => ({ ...prev, [key]: parseInt(quantity) || 0 }));
  };

  const handleSubmit = async () => {
    if (!openSession) return;
    setLoading(true);
    setError(null);

    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
        setError("Usuário não autenticado.");
        setLoading(false);
        return;
    }

    const counted_amount = Math.round(total * 100);

    const { error: insertError } = await supabase.from('cash_counts').insert({
        cash_session_id: openSession.id,
        user_id: user.id,
        counted_amount: counted_amount,
        details: counts,
        observations: observations,
    });

    if (insertError) {
        setError("Falha ao salvar a contagem. Verifique se a tabela 'cash_counts' existe. Detalhes: " + insertError.message);
        setLoading(false);
        return;
    }

    // Próximo passo: Atualizar a sessão de caixa para o status 'closed'
    // e calcular a diferença. Isso pode ser feito aqui ou com uma DB function.
    alert('Contagem salva com sucesso! Próximo passo seria fechar o caixa.');
    setLoading(false);
    // Idealmente, redirecionar para a página da sessão fechada.
  };

  if (loading && !openSession) {
    return <div>Verificando sessão de caixa...</div>;
  }

  if (error) {
    return <div className="text-red-500 p-4 bg-red-100 border border-red-400 rounded">{error}</div>;
  }

  return (
    <div className="max-w-4xl mx-auto">
      <h1 className="text-3xl font-bold text-gray-800 mb-6">Contagem de Dinheiro do Caixa</h1>
      
      <div className="bg-white shadow-md rounded-lg p-8">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Coluna de Contagem */}
          <div>
            <h3 className="text-lg font-semibold mb-4 border-b pb-2">Cédulas</h3>
            <div className="space-y-3">
              {denominations.notes.map(value => (
                <div key={`note_${value}`} className="grid grid-cols-3 items-center gap-2">
                  <label className="font-medium">R$ {value},00</label>
                  <input 
                    type="number" 
                    min="0" 
                    onChange={(e) => handleCountChange(value, 'notes', e.target.value)}
                    className="input-text text-right"
                    placeholder="Qtd."
                  />
                  <span className="text-right font-mono">{((counts[`notes_${value}`] || 0) * value).toFixed(2)}</span>
                </div>
              ))}
            </div>

            <h3 className="text-lg font-semibold mb-4 mt-8 border-b pb-2">Moedas</h3>
            <div className="space-y-3">
              {denominations.coins.map(value => (
                <div key={`coin_${value}`} className="grid grid-cols-3 items-center gap-2">
                  <label className="font-medium">R$ {value.toFixed(2)}</label>
                  <input 
                    type="number" 
                    min="0" 
                    onChange={(e) => handleCountChange(value, 'coins', e.target.value)}
                    className="input-text text-right"
                    placeholder="Qtd."
                  />
                  <span className="text-right font-mono">{((counts[`coins_${value}`] || 0) * value).toFixed(2)}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Coluna de Resumo */}
          <div className="bg-gray-50 p-6 rounded-lg">
            <h3 className="text-xl font-bold mb-4">Resumo da Contagem</h3>
            <div className="space-y-3">
                <div className="flex justify-between text-lg">
                    <span>Valor Inicial (Troco):</span>
                    <span className="font-mono">R$ {(openSession?.initial_amount / 100).toFixed(2)}</span>
                </div>
                 <div className="flex justify-between text-2xl font-bold border-t pt-4 mt-4">
                    <span>Total Contado:</span>
                    <span className="font-mono text-blue-600">R$ {total.toFixed(2)}</span>
                </div>
            </div>

            <div className="mt-8">
                <label htmlFor="observations" className="block text-sm font-medium text-gray-700">Observações</label>
                <textarea 
                    id="observations" 
                    rows={4} 
                    value={observations}
                    onChange={(e) => setObservations(e.target.value)}
                    className="mt-1 block w-full input-text"
                    placeholder="Alguma observação sobre a contagem?"
                />
            </div>

            <div className="mt-8">
                <button 
                    onClick={handleSubmit}
                    disabled={loading || total === 0}
                    className="w-full btn-primary text-lg"
                >
                    {loading ? 'Salvando...' : 'Salvar e Fechar Caixa'}
                </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
