/*
  IMPORTANTE: Esta página assume a existência de uma tabela `cash_movements` com a seguinte estrutura:

  CREATE TABLE cash_movements (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cash_session_id bigint NOT NULL REFERENCES cash_sessions(id),
      user_id bigint NOT NULL REFERENCES users(id),
      type text NOT NULL CHECK(type IN ('suprimento', 'sangria')),
      amount bigint NOT NULL, -- em centavos
      reason text,
      created_at timestampz DEFAULT now()
  );

  Como não posso criar ou alterar tabelas, o código abaixo pode falhar se a tabela não existir no Supabase.
*/
"use client";

import { useEffect, useState, FormEvent } from "react";
import { createClient } from "@/lib/supabase/client";
import { Database } from "@/lib/database.types";

// Tipos
type CashMovement = Database['public']['Tables']['cash_movements']['Row'] & {
  users: { username: string } | null;
};

type MovementType = 'suprimento' | 'sangria';

export default function CashMovementsPage() {
  const supabase = createClient();
  const [movements, setMovements] = useState<CashMovement[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [showForm, setShowForm] = useState<MovementType | null>(null);

  async function fetchData() {
    setLoading(true);
    setError(null);

    const { data, error } = await supabase
      .from("cash_movements")
      .select(`*, user:users!user_id(username)`)
      .order("created_at", { ascending: false });

    if (error) {
      setError("Falha ao buscar movimentações. Verifique se a tabela 'cash_movements' existe no banco de dados. Detalhes: " + error.message);
    } else {
      setMovements(data as CashMovement[] || []);
    }

    setLoading(false);
  }

  useEffect(() => {
    fetchData();
  }, []);

  const handleCloseForm = (needsReload: boolean) => {
    setShowForm(null);
    if (needsReload) {
      fetchData();
    }
  };
  
  const formatCurrency = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value / 100);
  const formatDate = (dateString: string) => new Date(dateString).toLocaleString('pt-BR');

  if (loading) {
    return <div>Carregando movimentações...</div>;
  }

  if (error) {
    return <div className="text-red-500 p-4 bg-red-100 border border-red-400 rounded">{error}</div>;
  }

  if (showForm) {
    return <MovementForm movementType={showForm} onClose={handleCloseForm} />;
  }

  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold text-gray-800">Movimentações de Caixa</h1>
        <div className="flex gap-4">
            <button onClick={() => setShowForm('suprimento')} className="btn-primary bg-green-600 hover:bg-green-700">+ Registrar Suprimento</button>
            <button onClick={() => setShowForm('sangria')} className="btn-primary bg-red-600 hover:bg-red-700">- Registrar Sangria</button>
        </div>
      </div>

      <div className="bg-white shadow-md rounded-lg overflow-hidden">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th className="th-base">Tipo</th>
              <th className="th-base">Valor</th>
              <th className="th-base">Motivo</th>
              <th className="th-base">Usuário</th>
              <th className="th-base">Data</th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {movements.map((m) => (
              <tr key={m.id} className="hover:bg-gray-50">
                <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <span className={`px-2 py-1 text-xs font-semibold rounded-full ${m.type === 'suprimento' ? 'text-green-800 bg-green-100' : 'text-red-800 bg-red-100'}`}>
                        {m.type}
                    </span>
                </td>
                <td className="td-base font-mono">{formatCurrency(m.amount)}</td>
                <td className="td-base">{m.reason || '-'}</td>
                <td className="td-base">{m.users?.username || 'N/A'}</td>
                <td className="td-base">{formatDate(m.created_at)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// --- Componente do Formulário ---

interface MovementFormProps {
  movementType: MovementType;
  onClose: (needsReload: boolean) => void;
}

import { useAuth } from "@/context/AuthContext";



// ... (rest of the file)



function MovementForm({ movementType, onClose }: MovementFormProps) {

    const { user } = useAuth(); // Usa o nosso AuthContext

    const [formData, setFormData] = useState({ amount: '', reason: '' });

    const [loading, setLoading] = useState(false);

    const [error, setError] = useState<string | null>(null);

    const [openSessionId, setOpenSessionId] = useState<number | null>(null);

    const supabase = createClient();



    useEffect(() => {

        async function findOpenSession() {

            setLoading(true);

            const { data, error } = await supabase

                .from('cash_sessions')

                .select('id')

                .eq('status', 'open')

                .single();



            if (error || !data) {

                setError('Nenhuma sessão de caixa aberta encontrada. É preciso abrir um caixa antes de registrar movimentações.');

            } else {

                setOpenSessionId(data.id);

            }

            setLoading(false);

        }

        findOpenSession();

    }, []);



    const handleSubmit = async (e: FormEvent) => {

        e.preventDefault();

        setError(null);



        if (!openSessionId) {

            setError('Erro de sessão. Não é possível continuar.');

            return;

        }



        const amountInCents = Math.round(parseFloat(formData.amount.replace(', ', '.')) * 100);

        if (isNaN(amountInCents) || amountInCents <= 0) {

            setError("Valor inválido.");

            return;

        }



        setLoading(true);

        

        if (!user) { // Verifica se o usuário do nosso contexto existe

            setError("Usuário não autenticado.");

            setLoading(false);

            return;

        }



        const { error: insertError } = await supabase.from('cash_movements').insert({

            cash_session_id: openSessionId,

            user_id: user.id, // Usa o ID do usuário do contexto

            type: movementType,

            amount: amountInCents,

            reason: formData.reason || null,

        });



        setLoading(false);



        if (insertError) {

            setError(insertError.message);

        } else {

            onClose(true);

        }

    };

    const title = movementType === 'suprimento' ? 'Registrar Suprimento' : 'Registrar Sangria';

    return (
        <div>
            <h2 className="text-2xl font-bold mb-6">{title}</h2>
            <form onSubmit={handleSubmit} className="p-8 bg-white shadow-md rounded-lg max-w-lg mx-auto">
                
                {error && <p className="mb-4 text-sm text-center text-red-600 p-3 bg-red-100 rounded">{error}</p>}

                <div className="mb-4">
                    <label htmlFor="amount" className="block text-sm font-medium text-gray-700">Valor (R$)</label>
                    <input type="text" name="amount" id="amount" value={formData.amount} onChange={(e) => setFormData({...formData, amount: e.target.value})} required className="mt-1 block w-full input-text" placeholder="Ex: 20,00" disabled={!openSessionId} />
                </div>

                <div className="mb-4">
                    <label htmlFor="reason" className="block text-sm font-medium text-gray-700">Motivo (Opcional)</label>
                    <input type="text" name="reason" id="reason" value={formData.reason} onChange={(e) => setFormData({...formData, reason: e.target.value})} className="mt-1 block w-full input-text" placeholder="Ex: Troco inicial, Retirada para despesas" disabled={!openSessionId} />
                </div>

                <div className="flex justify-end gap-4 mt-6">
                    <button type="button" onClick={() => onClose(false)} className="btn-secondary">Cancelar</button>
                    <button type="submit" disabled={loading || !openSessionId} className="btn-primary">
                        {loading ? "Salvando..." : "Salvar"}
                    </button>
                </div>
            </form>
        </div>
    );
}
