CREATE TABLE cash_movements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_session_id bigint NOT NULL REFERENCES cash_sessions(id),
    user_id bigint NOT NULL REFERENCES users(id),
    type text NOT NULL CHECK(type IN ('suprimento', 'sangria')),
    amount bigint NOT NULL, -- em centavos
    reason text,
    created_at timestamp with time zone DEFAULT now()
);