-- 1. Tabela para registrar o histórico de movimentações de estoque
CREATE TABLE stock_movements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES products(id),
    user_id bigint NOT NULL REFERENCES users(id),
    type text NOT NULL CHECK (type IN ('entrada', 'saida')),
    quantity numeric NOT NULL,
    reason text,
    created_at timestamp with time zone DEFAULT now()
);

-- 2. Função para ajustar o estoque de forma segura (atômica)
CREATE OR REPLACE FUNCTION adjust_stock(
    p_product_id bigint,
    p_user_id bigint,
    p_movement_type text,
    p_quantity numeric,
    p_reason text
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    stock_change numeric;
BEGIN
    -- Determina se a quantidade deve ser somada ou subtraída
    IF p_movement_type = 'entrada' THEN
        stock_change := p_quantity;
    ELSIF p_movement_type = 'saida' THEN
        stock_change := -p_quantity;
    ELSE
        RAISE EXCEPTION 'Tipo de movimento inválido: %', p_movement_type;
    END IF;

    -- Insere o registro da movimentação
    INSERT INTO stock_movements (product_id, user_id, type, quantity, reason)
    VALUES (p_product_id, p_user_id, p_movement_type, p_quantity, p_reason);

    -- Atualiza o estoque na tabela de produtos
    UPDATE products
    SET stock = stock + stock_change
    WHERE id = p_product_id;
END;
$$;