-- 1. Tabela para o histórico de movimentações de ITENS DE ESTOQUE
CREATE TABLE estoque_movements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id bigint NOT NULL REFERENCES estoque_itens(id),
    user_id bigint NOT NULL REFERENCES users(id),
    type text NOT NULL CHECK (type IN ('entrada', 'saida')),
    quantity numeric NOT NULL,
    reason text,
    created_at timestamp with time zone DEFAULT now()
);

-- 2. Função para ajustar o estoque de ITENS DE ESTOQUE
CREATE OR REPLACE FUNCTION adjust_estoque_item(
    p_item_id bigint,
    p_user_id bigint,
    p_movement_type text,
    p_quantity numeric,
    p_reason text
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    stock_change numeric;
BEGIN
    -- Determina se a quantidade deve ser somada ou subtraída
    IF p_movement_type = 'entrada' THEN
        stock_change := p_quantity;
    ELSIF p_movement_type = 'saida' THEN
        stock_change := -p_quantity;
    ELSE
        RAISE EXCEPTION 'Tipo de movimento inválido: %', p_movement_type;
    END IF;

    -- Insere o registro da movimentação
    INSERT INTO estoque_movements (item_id, user_id, type, quantity, reason)
    VALUES (p_item_id, p_user_id, p_movement_type, p_quantity, p_reason);

    -- Atualiza o estoque na tabela de itens de estoque
    UPDATE estoque_itens
    SET estoque_atual = estoque_atual + stock_change
    WHERE id = p_item_id;
END;
$$;